---

- hosts: all
  become: true
  tasks:
  - name: Start httpd service
    ansible.builtin.service:
      name: httpd
      state: stopped
  - name: install apache2 package
    dnf:
      name: httpd
      state: absent

